// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQgpWIFal4h1FeP3Tj0zFrSJsABq-e5Cw',
    appId: '1:670174331043:web:3dd8901e48973bb0f5ff16',
    messagingSenderId: '670174331043',
    projectId: 'chat-app-2e0b5',
    authDomain: 'chat-app-2e0b5.firebaseapp.com',
    storageBucket: 'chat-app-2e0b5.appspot.com',
    measurementId: 'G-10D4758R17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGcaGtXgPETsNH4MkFZaLrSFSu5m933Qo',
    appId: '1:670174331043:android:6a94d72589e46e7cf5ff16',
    messagingSenderId: '670174331043',
    projectId: 'chat-app-2e0b5',
    storageBucket: 'chat-app-2e0b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD4vJJGYiGOG-8CHBqolbjz2ex4ISY0EI',
    appId: '1:670174331043:ios:666d18dad4eed96ef5ff16',
    messagingSenderId: '670174331043',
    projectId: 'chat-app-2e0b5',
    storageBucket: 'chat-app-2e0b5.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD4vJJGYiGOG-8CHBqolbjz2ex4ISY0EI',
    appId: '1:670174331043:ios:9cb1256f2d8829c7f5ff16',
    messagingSenderId: '670174331043',
    projectId: 'chat-app-2e0b5',
    storageBucket: 'chat-app-2e0b5.appspot.com',
    iosBundleId: 'com.example.chatapp1.RunnerTests',
  );
}
